import { Word } from "./types";

export const defaultWords: Word[] = [
  { id: "w1", en: "abandon", ja: "捨てる、放棄する", example: "He abandoned his car in the snow.", partOfSpeech: "動詞" },
  { id: "w2", en: "ability", ja: "能力", example: "She has the ability to learn languages quickly.", partOfSpeech: "名詞" },
  { id: "w3", en: "absorb", ja: "吸収する", example: "Plants absorb water through their roots.", partOfSpeech: "動詞" },
  { id: "w4", en: "abundant", ja: "豊富な", example: "Fish were abundant in the river.", partOfSpeech: "形容詞" },
  { id: "w5", en: "accomplish", ja: "成し遂げる", example: "We accomplished our goal this year.", partOfSpeech: "動詞" },
  { id: "w6", en: "accurate", ja: "正確な", example: "The report was accurate and detailed.", partOfSpeech: "形容詞" },
  { id: "w7", en: "achieve", ja: "達成する", example: "She achieved great success in her career.", partOfSpeech: "動詞" },
  { id: "w8", en: "acknowledge", ja: "認める", example: "He acknowledged his mistake.", partOfSpeech: "動詞" },
  { id: "w9", en: "adapt", ja: "適応する", example: "Animals adapt to their environment.", partOfSpeech: "動詞" },
  { id: "w10", en: "adequate", ja: "十分な", example: "The salary was adequate for their needs.", partOfSpeech: "形容詞" },
  { id: "w11", en: "adjust", ja: "調整する", example: "Please adjust the volume.", partOfSpeech: "動詞" },
  { id: "w12", en: "advocate", ja: "提唱者、擁護する", example: "She is an advocate for human rights.", partOfSpeech: "名詞" },
  { id: "w13", en: "align", ja: "整列させる、一致させる", example: "Align the text to the center.", partOfSpeech: "動詞" },
  { id: "w14", en: "allocate", ja: "割り当てる", example: "The budget was allocated to each department.", partOfSpeech: "動詞" },
  { id: "w15", en: "ambiguous", ja: "曖昧な", example: "His answer was ambiguous.", partOfSpeech: "形容詞" },
  { id: "w16", en: "analyze", ja: "分析する", example: "We need to analyze the data carefully.", partOfSpeech: "動詞" },
  { id: "w17", en: "anticipate", ja: "予期する", example: "We anticipate a busy weekend.", partOfSpeech: "動詞" },
  { id: "w18", en: "apparent", ja: "明白な", example: "It became apparent that he was lying.", partOfSpeech: "形容詞" },
  { id: "w19", en: "appreciate", ja: "感謝する、評価する", example: "I appreciate your help.", partOfSpeech: "動詞" },
  { id: "w20", en: "approach", ja: "取り組み方、近づく", example: "We need a new approach to this problem.", partOfSpeech: "名詞" },
  { id: "w21", en: "appropriate", ja: "適切な", example: "Wear appropriate clothing for the interview.", partOfSpeech: "形容詞" },
  { id: "w22", en: "arbitrary", ja: "恣意的な", example: "The decision seemed arbitrary.", partOfSpeech: "形容詞" },
  { id: "w23", en: "aspect", ja: "側面", example: "Consider every aspect of the plan.", partOfSpeech: "名詞" },
  { id: "w24", en: "assume", ja: "想定する、思い込む", example: "Don't assume you know the answer.", partOfSpeech: "動詞" },
  { id: "w25", en: "attain", ja: "達成する、獲得する", example: "She attained a high level of skill.", partOfSpeech: "動詞" },
  { id: "w26", en: "attribute", ja: "属性、〜のせいにする", example: "He attributed his success to hard work.", partOfSpeech: "名詞" },
  { id: "w27", en: "authentic", ja: "本物の", example: "This is an authentic Italian recipe.", partOfSpeech: "形容詞" },
  { id: "w28", en: "benefit", ja: "利益、恩恵", example: "Exercise has many health benefits.", partOfSpeech: "名詞" },
  { id: "w29", en: "bias", ja: "偏見", example: "The study was free of bias.", partOfSpeech: "名詞" },
  { id: "w30", en: "capable", ja: "有能な、できる", example: "She is capable of solving hard problems.", partOfSpeech: "形容詞" },
  { id: "w31", en: "coherent", ja: "首尾一貫した", example: "He gave a coherent explanation.", partOfSpeech: "形容詞" },
  { id: "w32", en: "collaborate", ja: "協力する", example: "The two teams collaborated on the project.", partOfSpeech: "動詞" },
  { id: "w33", en: "compensate", ja: "埋め合わせる、補償する", example: "The company compensated him for the damage.", partOfSpeech: "動詞" },
  { id: "w34", en: "comprehensive", ja: "包括的な", example: "We need a comprehensive plan.", partOfSpeech: "形容詞" },
  { id: "w35", en: "conclude", ja: "結論づける", example: "The study concluded that exercise helps sleep.", partOfSpeech: "動詞" },
  { id: "w36", en: "consequence", ja: "結果、影響", example: "Every action has a consequence.", partOfSpeech: "名詞" },
  { id: "w37", en: "considerable", ja: "かなりの", example: "It took a considerable amount of time.", partOfSpeech: "形容詞" },
  { id: "w38", en: "consistent", ja: "一貫した", example: "Her performance has been consistent all year.", partOfSpeech: "形容詞" },
  { id: "w39", en: "constraint", ja: "制約", example: "We are working under time constraints.", partOfSpeech: "名詞" },
  { id: "w40", en: "contribute", ja: "貢献する", example: "Everyone contributed to the success.", partOfSpeech: "動詞" },
  { id: "w41", en: "convey", ja: "伝える", example: "The letter conveyed his feelings clearly.", partOfSpeech: "動詞" },
  { id: "w42", en: "crucial", ja: "極めて重要な", example: "Sleep is crucial for good health.", partOfSpeech: "形容詞" },
  { id: "w43", en: "cumulative", ja: "累積的な", example: "The cumulative effect was significant.", partOfSpeech: "形容詞" },
  { id: "w44", en: "definitive", ja: "決定的な", example: "There is no definitive answer yet.", partOfSpeech: "形容詞" },
  { id: "w45", en: "demonstrate", ja: "示す、実演する", example: "The teacher demonstrated the experiment.", partOfSpeech: "動詞" },
  { id: "w46", en: "derive", ja: "由来する、引き出す", example: "The word derives from Latin.", partOfSpeech: "動詞" },
  { id: "w47", en: "distinct", ja: "明確に異なる", example: "The two ideas are quite distinct.", partOfSpeech: "形容詞" },
  { id: "w48", en: "diverse", ja: "多様な", example: "The city has a diverse population.", partOfSpeech: "形容詞" },
  { id: "w49", en: "eliminate", ja: "排除する", example: "We need to eliminate all errors.", partOfSpeech: "動詞" },
  { id: "w50", en: "emphasize", ja: "強調する", example: "The teacher emphasized the importance of practice.", partOfSpeech: "動詞" },
];
